name: Flow Type Checking

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  flow-check:
    runs-on: ubuntu-latest
    name: Flow Type Check

    steps:
      - uses: actions/checkout@v4

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Cache Flow libdefs
        uses: actions/cache@v4
        with:
          path: .flow-typed
          key: ${{ runner.os }}-flow-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-flow-

      - name: Install Flow libdefs
        run: npm run flow-typed || true

      - name: Run Flow type checking
        run: npm run flow:check