name: Lint and test

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: 'production'

    services:
      redis:
        image: 'redis:8.0.1'
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Setup on Redis
        env:
          SETUP: >-
            {
              "url": "http://127.0.0.1:4567/forum",
              "secret": "abcdef",
              "admin:username": "admin",
              "admin:email": "test@example.org",
              "admin:password": "hAN3Eg8W",
              "admin:password:confirm": "hAN3Eg8W",

              "database": "redis",
              "redis:host": "127.0.0.1",
              "redis:port": 6379,
              "redis:password": "",
              "redis:database": 0
            }
          CI: >-
            {
              "host": "127.0.0.1",
              "database": 1,
              "port": 6379
            }
        run: |
          node app --setup="${SETUP}" --ci="${CI}"

      - name: Run ESLint
        run: npm run lint

      - name: Clean up flow-typed definitions
        run: |
          echo "Checking if flow-typed exists before cleanup"
          ls -la | grep flow-typed || echo "No flow-typed directory found"
          rm -rf flow-typed || echo "No flow-typed to remove"
          echo "Checking if flow-typed exists after cleanup"
          ls -la | grep flow-typed || echo "No flow-typed directory found after cleanup"

      - name: Run Flow type checking
        run: |
          echo "Running flow check..."
          echo "Current directory contents:"
          ls -la
          echo "Checking for flow-typed:"
          find . -name "flow-typed" -type d || echo "No flow-typed directories found"
          echo "FLOW_VERSION and environment:"
          which flow
          flow --version
          echo "Flow configuration:"
          cat .flowconfig
          npm run flow:check 2>&1 | head -20
          echo "Flow check completed"

      - name: Node tests
        run: npm test

      - name: Extract coverage info
        run: npm run coverage

      - name: Test coverage
        uses: coverallsapp/github-action@v2